"""create configurations and signals tables

Revision ID: 8d35cd396a73
Revises: 
Create Date: 2026-06-18 09:38:03.719010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d35cd396a73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS signals")
    op.create_table('configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trend_timeframe', sa.String(length=10), nullable=False),
    sa.Column('context_timeframe', sa.String(length=10), nullable=True),
    sa.Column('entry_timeframe', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='signals'
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('trend_timeframe', sa.String(length=10), nullable=False),
    sa.Column('context_timeframe', sa.String(length=10), nullable=True),
    sa.Column('entry_timeframe', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('signal_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('candle_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='signals'
    )
    op.create_index('idx_signals_symbol', 'signals', ['symbol'], unique=False, schema='signals')
    op.create_index('idx_signals_time', 'signals', ['signal_time'], unique=False, schema='signals')
    op.create_index('idx_signals_user_id', 'signals', ['user_id'], unique=False, schema='signals')
    op.execute("CREATE INDEX idx_signals_user_time ON signals.signals (user_id, signal_time DESC)")
    op.create_index('uq_signals_dedup', 'signals', ['user_id', 'dedup_key', 'candle_time'], unique=True, schema='signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_signals_dedup', table_name='signals', schema='signals')
    op.drop_index('idx_signals_user_time', table_name='signals', schema='signals')
    op.drop_index('idx_signals_user_id', table_name='signals', schema='signals')
    op.drop_index('idx_signals_time', table_name='signals', schema='signals')
    op.drop_index('idx_signals_symbol', table_name='signals', schema='signals')
    op.drop_table('signals', schema='signals')
    op.drop_table('configurations', schema='signals')
    # ### end Alembic commands ###
