syntax = "proto3";

package market_data;

service MarketDataService {
  rpc GetCandles(GetCandlesRequest) returns (GetCandlesResponse);
  rpc GetSymbols(GetSymbolsRequest) returns (GetSymbolsResponse);
}

message CandleDto {
  int64 timestamp = 1;
  double open = 2;
  double high = 3;
  double low = 4;
  double close = 5;
  double volume = 6;
}

message SymbolDto {
  string symbol = 1;
}

message GetCandlesRequest {
  string symbol = 1;
  string timeframe = 2;
  int32 count = 3;
}

message GetSymbolsRequest {
  string search = 1;
}

message GetCandlesResponse {
  repeated CandleDto candles = 1;
}

message GetSymbolsResponse {
  repeated SymbolDto symbols = 1;
}
